course : TESTTTTTTTTTTTTTTTTT

spring: 
  datasource:
    url: "jdbc:mysql://localhost:3306/testStudentsDbTwo?useSSL=false"
    username: student2
    password: "{cipher}AQBrQYKpr7Fh70aHmJ6ubKLdPx0m9X9vgtegRx3oX8qd0OR9bCf8tC4MHj/IRbDtU6DW/LMg0Tdf6VdUkh/ewaRMk5Ja40Pu+9CitgXidesLe9dxf/BTKmsCmZJN28XbJHzbEKIF+xTl3IAx00fXA4jEdnEkSlGvja2kNioaZSWk7499RguJkJfo+djIz35fjA9nq6uA3XdCXzqut6i4FYGAnBoghMVE5LQN/+9cSOWxxrlSZkGoN7ABk5yxYlKHG4Ke+jkCfIWkswFG72cAv+p5VKjmIc1lu1+0xCAfjd6Hzfmz5pi9ufhyuhEfNJm2tZVKWfDfbBUQ4NfgixSKsu9oI5wb31WwTckuZQyLsh635RKZSXRPe99XURohb2g9bl4="
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
