spring:
      profiles: local
      multitenancy:
            datasources: 
                - 
                  tenantId: tenant_1
                  url: "jdbc:mysql://localhost:3306/testStudentsDbOne?useSSL=false"
                  username: student1
                  password: student1
                - 
                  tenantId: tenant_2
                  url: "jdbc:mysql://localhost:3306/testStudentsDbTwo"
                  username: student2
                  password: student2

      jpa: 
          hibernate:
                   ddl-auto : update
          show-sql: true
          properties: 
                     hibernate:
                              jdbc: 
                                  time_zone: UTC
      jackson:
              serialization:
                           fail-on-empty-beans: false
