spring:
      profiles: local
         datasource: 
            url: "jdbc:mysql://localhost:3306/testStudentsDbOne?useSSL=false"
            username: student1
            password: student1

      jpa: 
          hibernate:
                   ddl-auto : update
          show-sql: true
          properties: 
                     hibernate:
                              jdbc: 
                                  time_zone: UTC
      jackson:
              serialization:
                           fail-on-empty-beans: false
                           
course: TestComputerScience                           
