course : ABCDEFRRRR

spring: 
  datasource:
    url: "jdbc:mysql://localhost:3306/testStudentsDbOne?useSSL=false"
    username: student1
    password: "{cipher}AQCa5rmBhRb+4fDW8kgJjAxGhVtXs4+KPeUdNi+maU2Bm58OQlbGB0BzejJ47ru8bPt/vM694S3Wx7cimU6cf8ECE54DvM+ch80v3dlCilh6BT2ZiS33C8nLBZOVtuJyJv3852f6A5FaCPz5knylDZ4PcEAGdsb7WCn1KqWJjzb++oMdEA/Lk0/ou06DoCvdA0l7e0P+tBWtpP3nTV9FMWXwQ/qrOVKuBlleIiyWePHMOIsEcmURBt78mMlGmhn7Lp4EnIaBMZDvm3DPMcwlI9OI3keAu+NcVUK1qXov7fkPwyx4U8BTyrH5v6P1G8EFh0rMmRWqKS3CpfVzs5nklg7MbDK3qjdmSrRQoZjuHegPGDHHOkmXGecQ93l4XjT8drI="
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
