course : ABCDEFRRRR

spring: 
  datasource:
    url: "jdbc:mysql://localhost:3306/testStudentsDbTwo?useSSL=false"
    username: student2
    password: "{cipher}AQAi1mK30KKP3wXLHzHZeT3Vxqj+782kDWhJq27cqJyqyDsZz1/oicFscM0Jf+1jLmi7gY/YfvLQE9BoKX+L8Gu0y+LDfkAEa0Oo7ZVo6qR+RYmcXtu3fU7PDVhS0wLgjTmSdXbPnDn9RbKUlaRJgEeUsxH4BUQg2FVNmJSXmtxWhcLFodia5aX2Pq3D0DMbHJQCg+ORb3D3/4sGArrqaj1MF+3VCKdSy+tLOWGp7bx9dY0wQl55bQy9I9ctJXCCPY/+0QwkK7gv2d6tC7/qvql0WwaF8HDuhFNGyo1Xd3WVI04l+pfI2HsLox3gGYVdyBspOTA+zs1XV8MbizcN5lq5iZUf3dhM9rTrHTnfIcDFuJoC6vLfATCCJGDBqBKVbLE="
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
