server:
  port: 6063
spring: 
  datasource:
    url: "jdbc:mysql://localhost:3306/examHallDb?useSSL=false"
    username: test1
    password: test1
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    open-in-view: false
  application:
    name: exam-halls-service
